### ISSUE TITLE
Mismatch between panorama_to_region.txt and .house 

### ISSUE THREAD

**Issue by khanhptnk** [niessner/Matterport#11]
In scan p5wJjkQkbXX, viewpoint aac9edb8b1c845bc8450c8b68ab24bef is classified as in region 1 (a garage) but in panorama_to_region.txt, it is classified as in region 29 (a living room). 
panorama_to_region.txt seems to be correct but then how was the data in the .house file generated?

**Comment by tomfunkhouser** [comment]
In the updated .house file, panorama "aac9edb8b1c845bc8450c8b68ab24bef" is classified as in region 29 (a living room), as it should be.  Here is the line from p5wJjkQkbXX.house  ...

P  aac9edb8b1c845bc8450c8b68ab24bef  108 29  0  -7.77579 7.43986 1.51952  0 0 0 0 0

**Comment by khanhptnk** [comment]
Thanks. When were the .house files updated?
