### ISSUE TITLE
Download server does not respond

### ISSUE THREAD

**Issue by khanhptnk** [niessner/Matterport#27]
Hi, 

I used the `download_mp.py` script but the server didn't respond. Was there any sever change recently? I obtained the script about 1 year ago.

I ran the following command:

`python download_mp.py --type undistorted_camera_parameters -o . `

**Comment by alpc72** [comment]
I have the same problem. Is the sever accessible now? I can visit about 4 months ago, but it can't be accessed recently. Can anybody help?

**Comment by alpc72** [comment]
> Hi,
> 
> I used the `download_mp.py` script but the server didn't respond. Was there any sever change recently? I obtained the script about 1 year ago.
> 
> I ran the following command:
> 
> `python download_mp.py --type undistorted_camera_parameters -o . `

Can you download now?

**Comment by khanhptnk** [comment]
The authors changed the download server. I emailed the authors (matterport3d@googlegroups.com) and obtained the new `download_mp.py` file.

**Comment by zwx8981** [comment]
@khanhptnk Hi, can you share me the new download_mp.py file? Thank you so much!
