### ISSUE TITLE
Hi,  could you pls give me an example command of generating segmenation image?

### ISSUE THREAD

**Issue by Jian-danai** [niessner/Matterport#29]
I learned that : mpview usage is as follows
Usage: **mpview [inputfiles] [options]**
Options:
  -input_house <filename> : input region segmentations file (e.g., xxx/region_segmentations/xxx.house)
  -input_scene <filename> : input textured mesh (e.g., xxx/matterport_mesh/*/*.obj)
  -input_mesh <filename> : input poisson mesh (e.g., xxx/poisson_meshes/xxx_11.ply)
  -input_categories <filename> : input categories tsv file (e.g., metadata/*.tsv)
  -input_segments <filename> : input json file with face segments (e.g., xxx/object_segmentations/*.fsegs.json)
  -input_objects <filename> : input json file with objects and labels (e.g., xxx/object_segmentations/*.semseg.json)
  -input_configuration <filename> : input file with images and panorama (e.g., xxx/undistorted_camera_parameters/xxx.conf)
  -output_image <filename> : save an image to <filename> and exit
  -background <r> <g> <b> : background color (with each component in [0.0-1.0])
  -window <width> <height> : window size in pixels
  -camera <ex> <ey> <ez> <tx> <ty> <tz> <ux> <uy> <uz> : initial camera extrinsics
  -batch : exit without starting interactive viewer
  -v : print verbose (recommended)

Typical usage for viewing house segmentations:
  cd scans/17DRP5sb8fy (or any other house)
  mpview -input_house house_segmentations/*.house -v   OR
  mpview -input_house house_segmentations/*.house -input_scene matterport_mesh/*/*.obj -v   OR
  mpview -input_house house_segmentations/*.house -input_mesh house_segmentations/*.ply -v

But when I add [inputfiles] with an image file, for example: _mpview ~/mp_undistort_color/29hnd4uzFmX/undistorted_color_images/ffe91becf15c455ca85be73f029db24a_i2_4.jpg  -input_segments 29hnd4uzFmX.fsegs.json -output_image outputsegmenation.png_
I got this error: Invalid program argument: ~/mp_undistort_color/29hnd4uzFmX/undistorted_color_images/ffe91becf15c455ca85be73f029db24a_i2_4.jpg

Then how to input an undistorted_color_image and output a segmenation_images like this?
![image](https://user-images.githubusercontent.com/42494274/65978387-336d0e80-e4a6-11e9-94a4-bd092363c2e6.png)

**Comment by xiong224** [comment]
Hello，have you got the 2D semantic segmentation labels? I am a 
college students in China, too.

**Comment by fuenwang** [comment]
Hi @Jian-danai , do you found out how to generate segmentation images? I also have same question :(

**Comment by Jian-danai** [comment]
> Hi @Jian-danai , do you found out how to generate segmentation images? I also have same question :(

**Comment by g-gaurav** [comment]
hi @Jian-danai did you get something. if yes then pls share.
