### ISSUE TITLE
house_segmentations format

### ISSUE THREAD

**Issue by khanhptnk** [niessner/Matterport#9]
I discovered that the region rows ('R' rows) have only **four** zeros instead of **five** zeros as described in https://github.com/niessner/Matterport/blob/master/data_organization.md. At the positions of the zeros are float numbers. Is it something to be concerned?

**Comment by tomfunkhouser** [comment]
The documentation was wrong.    The fifth-to-last value in the "R" rows 
of the .house files represents the height of the region (from the floor 
to the top).   There should only be four zeroes at the end of each line 
(as there are).   The documentation has been updated.   Sorry for the 
confusion.

**Comment by khanhptnk** [comment]
Thank you very much!
